blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/software-mansion/react-native-reanimated/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Feature request
    url: https://github.com/software-mansion/react-native-reanimated/discussions/categories/ideas
    about: Please submit feature requests here.
