name: Babel plugin static check
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths:
      - '.github/workflows/babel-plugin-static-check.yml'
      - 'packages/react-native-reanimated/plugin/**'
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - '.github/workflows/babel-plugin-static-check.yml'
      - 'packages/react-native-reanimated/plugin/**'
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    concurrency:
      group: plugin-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - name: Clear annotations
        run: .github/workflows/helper/clear-annotations.sh

      - name: Install monorepo dependencies
        run: yarn install --immutable
      - name: Build Reanimated
        working-directory: packages/react-native-reanimated
        run: yarn build

      - name: Diff
        id: diff
        run: git update-index --refresh && git diff-index --quiet HEAD --
      - name: Show diff
        if: failure() && steps.diff.outcome == 'failure'
        run: git diff
      - name: Check types
        working-directory: packages/react-native-reanimated
        run: yarn typecheck:plugin
      - name: Lint and format
        working-directory: packages/react-native-reanimated
        run: yarn lint:plugin
      - name: Test
        working-directory: packages/react-native-reanimated
        run: yarn jest plugin
      - name: Check Example App bundling
        working-directory: apps/paper-example
        run: yarn && yarn react-native bundle --reset-cache --entry-file='App.tsx' --bundle-output='/dev/null' --dev=true --platform='ios'
