name: Build npm package

on:
  schedule:
    - cron: '0 12 */1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d

      - name: Build package
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: >-
          ./createNPMPackage.sh

      - name: Upload npm package
        uses: actions/upload-artifact@v2
        with:
          name: react-native-reanimated-2.0.0-alpha.tgz
          path: '*.tgz'
