name: Build release npm package, Reanimated test

on:
  push:
  workflow_dispatch:

jobs:
  call-build-workflow-rea-test:
    uses: ./.github/workflows/build-npm-package.yml
    with:
      version: release
      ref: '@piaskowyk/2.9.1'
