name: Build npm package
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  workflow_call:
    inputs:
      option:
        required: false
        type: string
      ref:
        required: false
        type: string
      upload_binaries:
        required: false
        type: boolean
      publish_on_npm:
        required: false
        type: boolean
    secrets:
      NODE_AUTH_TOKEN:
        required: false

jobs:
  build:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Clear annotations
        run: scripts/clear-annotations.sh

      - name: Set up JDK 11
        if: ${{ inputs.ref == 'Reanimated2' }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install NDK
        if: ${{ inputs.ref == 'Reanimated2' }}
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d

      - name: Build package
        id: build
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: >-
          ./createNPMPackage.sh ${{ inputs.option }} 2> build.log

      - name: Check if any node_modules were packed
        id: node_modules
        run: >-
          ! grep --silent -E "node_modules/.+"

      - name: Check if size is over 1MB
        if: ${{ inputs.ref != 'Reanimated2' }}
        id: size
        run: grep --silent -E "npm notice package size:\s*[0-9][0-9]?[0-9]?(\.[0-9]*)?\s*kB" build.log

      - name: Show build log
        if: failure() && steps.build.outcome == 'failure'
        run: >-
          cat build.log

      - name: Show packed node_modules
        if: failure() && steps.node_modules.outcome == 'failure'
        run: >-
          ! grep -E "node_modules/.+"

      - name: Show exceeded package size
        if: failure() && steps.size.outcome == 'failure'
        run: grep -E "npm notice package size:" build.log

      - run: echo "PACKAGE_NAME=$(ls -l | egrep -o "react-native-reanimated-(.*)(=?\.tgz)")" >> $GITHUB_ENV

      - name: Upload npm package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: '*.tgz'

      - name: Compress Android build output
        if: ${{ inputs.upload_binaries }}
        run: zip -r android-build-output.zip build_output

      - name: Upload Android build folder
        if: ${{ inputs.upload_binaries }}
        uses: actions/upload-artifact@v4
        with:
          name: android-build-output
          path: android-build-output.zip
          retention-days: 5

      - run: npm publish $PACKAGE_NAME --tag nightly
        if: ${{ inputs.publish_on_npm }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
