name: Check for stale issues
on:
  schedule:
    - cron: '37 21 * * *' # at 21:37 every day
  issues:
    types: [edited]
  issue_comment:
    types: [created, edited]
  workflow_dispatch:

jobs:
  main:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: 'software-mansion-labs/swmansion-bot'
          ref: stable

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Actions
        run: yarn install

      - name: Close when stale
        uses: ./close-when-stale
        with:
          close-when-stale-label: 'Close when stale'
          days-to-close: 20
