name: Test docs build

on:
  pull_request:
    paths:
      - '.github/workflows/docs-check.yml'
      - 'docs/**'
  merge_group:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: docs
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Clear annotations
        run: scripts/clear-annotations.sh

      - name: Install node dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn
      - name: Lint check docs
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn lint
      - name: Build docs
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn build
