name: docs publish
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  push:
    branches:
      - main
    paths:
      - docs/docs-reanimated/**
      - docs/docs-worklets/**
      - packages/react-native-reanimated/compatibility.json
      - packages/react-native-worklets/compatibility.json
  workflow_dispatch:

jobs:
  docs-publish:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    env:
      REANIMATED_DOCS_DIR: docs/docs-reanimated
      WORKLETS_DOCS_DIR: docs/docs-worklets
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install monorepo node dependencies
        run: yarn install

      - name: Build Reanimated and Worklets docs
        uses: ./.github/actions/docs-build
        with:
          REANIMATED_DOCS_DIR: ${{ env.REANIMATED_DOCS_DIR }}
          WORKLETS_DOCS_DIR: ${{ env.WORKLETS_DOCS_DIR }}

      - name: Publish Reanimated and Worklets docs to GitHub Pages
        uses: ./.github/actions/docs-publish
        with:
          REANIMATED_DOCS_DIR: ${{ env.REANIMATED_DOCS_DIR }}
          WORKLETS_DOCS_DIR: ${{ env.WORKLETS_DOCS_DIR }}
