name: docs publish
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  push:
    branches:
      - main
    paths:
      - docs/docs-reanimated/**
      - docs/docs-worklets/**
      - packages/react-native-reanimated/compatibility.json
      - packages/react-native-worklets/compatibility.json
  workflow_dispatch:

jobs:
  docs-publish:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    env:
      REANIMATED_DOCS_DIR: docs/docs-reanimated
      WORKLETS_DOCS_DIR: docs/docs-worklets
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install monorepo node dependencies
        run: yarn install

      - name: Build Reanimated and Worklets docs
        uses: ./.github/actions/docs-build
        with:
          REANIMATED_DOCS_DIR: ${{ env.REANIMATED_DOCS_DIR }}
          WORKLETS_DOCS_DIR: ${{ env.WORKLETS_DOCS_DIR }}

      - name: Configure git user info
        run: >-
          git config --local user.email "action@github.com"
          && git config --local user.name "GitHub Action"

      - name: Bundle Worklets docs into Reanimated docs
        working-directory: ${{ env.WORKLETS_DOCS_DIR }}
        run: yarn prepublish

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          FOLDER: ${{ env.REANIMATED_DOCS_DIR }}/build
          BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
