name: Example Typescript check and lint
env:
  YARN_ENABLE_HARDENED_MODE: 0
  TYPE_CHECK_DIRECTORIES: >-
    apps/common-app
    apps/tvos-example
on:
  pull_request:
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory: [
            apps/common-app,
            apps/fabric-example,
            apps/macos-example,
            # apps/next-example, # next-example doesn't use TypeScript.
            apps/tvos-example,
            apps/web-example,
          ]
    concurrency:
      group: typescript-${{ matrix.working-directory }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - name: Clear annotations
        run: .github/workflows/helper/clear-annotations.sh

      - name: Install monorepo node dependencies
        run: yarn install --immutable
      - name: Build Reanimated package
        working-directory: packages/react-native-reanimated
        run: yarn build

      - name: Check types
        working-directory: ${{ matrix.working-directory }}
        if: ${{ contains(env.TYPE_CHECK_DIRECTORIES, matrix.working-directory) }}
        run: yarn tsc --noEmit
      - name: Lint
        working-directory: ${{ matrix.working-directory }}
        run: yarn lint
      - name: Build WebExample
        working-directory: ${{ matrix.working-directory }}
        if: ${{ matrix.working-directory == 'apps/web-example' }}
        run: yarn build
