name: Example iOS build check
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths:
      - .github/workflows/example-ios-build-check.yml
      - .github/actions/install-pods/**
      - .github/actions/cache-derived-data/**
      - packages/react-native-reanimated/RNReanimated.podspec
      - packages/react-native-reanimated/scripts/reanimated_utils.rb
      - packages/react-native-reanimated/apple/**
      - packages/react-native-reanimated/Common/**
      - packages/react-native-worklets/RNWorklets.podspec
      - packages/react-native-worklets/scripts/worklets_utils.rb
      - packages/react-native-worklets/apple/**
      - packages/react-native-worklets/Common/**
      - apps/fabric-example/**
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/example-ios-build-check.yml
      - .github/actions/install-pods/**
      - .github/actions/cache-derived-data/**
      - packages/react-native-reanimated/RNReanimated.podspec
      - packages/react-native-reanimated/scripts/reanimated_utils.rb
      - packages/react-native-reanimated/apple/**
      - packages/react-native-reanimated/Common/**
      - packages/react-native-worklets/RNWorklets.podspec
      - packages/react-native-worklets/scripts/worklets_utils.rb
      - packages/react-native-worklets/apple/**
      - packages/react-native-worklets/Common/**
      - apps/fabric-example/**
  workflow_call:
    inputs:
      bundleMode:
        required: false
        type: boolean
        default: false
  workflow_dispatch:

jobs:
  example-ios-build-check:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: macos-26
    env:
      WORKING_DIRECTORY: apps/fabric-example
      REANIMATED_DIR: packages/react-native-reanimated
    concurrency:
      group: ios-${{ github.ref }}-${{ inputs.bundleMode }}
      cancel-in-progress: true
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a `.ruby-version` or `.tool-versions`
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install monorepo node dependencies
        run: yarn install --immutable
      - name: Toggle Bundle Mode
        if: ${{ inputs.bundleMode }}
        run: ./scripts/toggle-bundle-mode.sh
      - name: Build Reanimated package
        working-directory: ${{ env.REANIMATED_DIR }}
        run: yarn build

      - name: Install Pods (with caching)
        uses: ./.github/actions/install-pods
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          pod-directory: ios

      - name: Cache DerivedData
        uses: ./.github/actions/cache-derived-data
        with:
          platform: ios
          working-directory: ${{ env.WORKING_DIRECTORY }}
          pod-directory: ios

      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}/ios
        run: xcodebuild -workspace FabricExample.xcworkspace -configuration Debug -scheme "Debug FabricExample" -destination "generic/platform=iOS Simulator" -quiet
