name: Example Next build check and tests
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths:
      - .github/workflows/example-next-build-check-and-test.yml
      - 'packages/react-native-reanimated/src/**'
      - 'packages/react-native-worklets/src/**'
      - 'apps/next-example/**'
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  example-next-build-check-and-test:
    runs-on: ubuntu-latest
    concurrency:
      group: build-next-example-${{ github.ref }}
      cancel-in-progress: true
    env:
      WORKING_DIRECTORY: apps/next-example
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
      - name: Install monorepo node dependencies
        run: yarn install --immutable
      - name: Build packages
        run: yarn build
      - name: Install Cypress dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn cypress install

      - name: Compile production build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn build:next

      - name: Run e2e tests
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn e2e:headless
