name: Test iOS build
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths:
      - .github/workflows/ios-build.yml
      - packages/react-native-reanimated/RNReanimated.podspec
      - packages/react-native-reanimated/scripts/reanimated_utils.rb
      - packages/react-native-reanimated/apple/**
      - packages/react-native-reanimated/Common/**
      - apps/paper-example/package.json
      - apps/paper-example/ios/**
      - packages/react-native-reanimated/FabricExample/package.json
      - packages/react-native-reanimated/FabricExample/ios/**
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/ios-build.yml
      - packages/react-native-reanimated/RNReanimated.podspec
      - packages/react-native-reanimated/scripts/reanimated_utils.rb
      - packages/react-native-reanimated/apple/**
      - packages/react-native-reanimated/Common/**
      - apps/paper-example/package.json
      - apps/paper-example/ios/**
      - packages/react-native-reanimated/FabricExample/package.json
      - packages/react-native-reanimated/FabricExample/ios/**

jobs:
  build:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: macos-14
    strategy:
      matrix:
        working-directory:
          [apps/paper-example, packages/react-native-reanimated/FabricExample]
      fail-fast: false
    concurrency:
      group: ios-${{ matrix.working-directory }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install monorepo node dependencies
        run: yarn install
      - name: Restore Reanimated node_modules from cache
        uses: actions/cache@v3
        with:
          path: packages/react-native-reanimated/node_modules
          key: ${{ runner.os }}-node-modules-reanimated-${{ hashFiles('packages/react-native-reanimated/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-reanimated-

      - name: Install Reanimated node dependencies
        working-directory: packages/react-native-reanimated
        run: yarn install

      - name: Restore app node_modules from cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.working-directory }}/node_modules
          key: ${{ runner.os }}-node-modules-${{ matrix.working-directory }}-${{ hashFiles(format('{0}/yarn.lock', matrix.working-directory)) }}
          restore-keys: ${{ runner.os }}-node-modules-${{ matrix.working-directory }}-

      - name: Install app node_modules
        working-directory: ${{ matrix.working-directory }}
        run: yarn install

      - name: Restore Pods from cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ matrix.working-directory }}/ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ matrix.working-directory }}-${{ hashFiles(format('{0}/ios/Podfile.lock', matrix.working-directory)) }}

      - name: Install Pods
        working-directory: ${{ matrix.working-directory }}/ios
        run: |
          bundle install
          bundle exec pod install

      - name: Restore build artifacts from cache
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-ios-derived-data-${{ matrix.working-directory }}-${{ hashFiles(format('{0}/ios/Podfile.lock', matrix.working-directory)) }}

      - name: Build app
        working-directory: ${{ matrix.working-directory }}
        run: npx react-native run-ios --no-packager
