name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
    paths: docs/**

jobs:
  publish:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Generate awesome content
        run: >-
          git config --local user.email "action@github.com"
          && git config --local user.name "GitHub Action"
          && cd docs
          && yarn
          && yarn build

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          FOLDER: docs/build
          BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
