name: Monorepo static checks
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths-ignore:
      - packages/
      - apps/
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - packages/
      - apps/
  workflow_call:
  workflow_dispatch:

jobs:
  monorepo-static-checks:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    concurrency:
      group: monorepo-static-checks-${{ github.ref }}
      cancel-in-progress: true
    steps:
      # Setup VM
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      # Setup repo
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build worklets
        run: yarn run build:worklets

      - name: Build reanimated
        run: yarn run build:reanimated

      # Checks
      - name: Lint
        run: yarn lint:root
