name: NPM Reanimated package build
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  workflow_call:
    inputs:
      option:
        required: false
        type: string
      ref:
        required: false
        type: string
      publish_on_npm:
        required: false
        type: boolean
  workflow_dispatch:
    inputs:
      option:
        required: false
        type: string
      ref:
        required: false
        type: string

jobs:
  npm-reanimated-package-build:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      REANIMATED_DIR: packages/react-native-reanimated
      PACKAGE_NAME: PLACEHOLDER # Will be reassigned later on.
      TAG: PLACEHOLDER # Will be reassigned later on.
      REANIMATED_VERSION: PLACEHOLDER # Will be reassigned later on.
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/

      # Ensure npm 11.5.1 or later is installed for OIDC
      - name: Update npm
        run: npm install -g npm@latest

      - name: Clear annotations
        run: .github/workflows/helper/clear-annotations.sh

      - name: Determine release tag
        if: ${{ inputs.publish_on_npm }}
        working-directory: ${{ env.REANIMATED_DIR }}
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "REANIMATED_VERSION=$VERSION" >> $GITHUB_ENV
          if [[ $VERSION == 3.* ]]; then
            echo "TAG=reanimated3-nightly" >> $GITHUB_ENV
          elif [[ $VERSION == 4.* ]]; then
            echo "TAG=nightly" >> $GITHUB_ENV
          else
            echo "There's no nightly release tag for version: $VERSION"
            exit 1
          fi
      - name: Assert TAG
        if: ${{ inputs.publish_on_npm && env.TAG == 'PLACEHOLDER' }}
        run: exit 1 # This should never happen.

      - name: Install monorepo node dependencies
        run: yarn install --immutable

      - name: Bump version for Reanimated 3 nightly release
        if: ${{ inputs.publish_on_npm && env.TAG == 'reanimated3-nightly' }}
        working-directory: ${{ env.REANIMATED_DIR }}
        run: |
          VERSION=${{ env.REANIMATED_VERSION }}
          MAJOR=$(echo $VERSION | awk -F. '{print $1}')
          MINOR=$(echo $VERSION | awk -F. '{print $2}')
          NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
          node ./scripts/set-reanimated-version.js $NEW_VERSION

      - name: Build package
        working-directory: ${{ env.REANIMATED_DIR }}
        id: build
        run: >-
          ./createNPMPackage.sh ${{ inputs.option }}

      - name: Add package name to env
        working-directory: ${{ env.REANIMATED_DIR }}
        run: echo "PACKAGE_NAME=$(ls -l | egrep -o "react-native-reanimated-(.*)(=?\.tgz)")" >> $GITHUB_ENV

      - name: Assert PACKAGE_NAME
        if: ${{ env.PACKAGE_NAME == 'PLACEHOLDER' }}
        run: exit 1 # This should never happen.

      - name: Upload npm package to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: '${{env.REANIMATED_DIR}}/${{ env.PACKAGE_NAME }}'

      - name: Move package to monorepo root
        # Running `--provenance` in the workspace breaks.
        run: mv ${{ env.REANIMATED_DIR }}/${{ env.PACKAGE_NAME }} .

      - name: Publish npm package
        run: npm publish $PACKAGE_NAME --tag ${{env.TAG}} --provenance
        if: ${{ inputs.publish_on_npm }}
