name: React Native nightly Reanimated build check [Nightly]
env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: 0
on:
  pull_request:
    paths:
      - .github/workflows/react-native-nightly-reanimated-build-check-nightly.yml
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    concurrency:
      group: build-v8-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          path: 'reanimated_repo'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Create React Native app
        run: npx react-native init app
      - name: Install dependencies
        working-directory: app
        run: yarn install
      - name: Install Reanimated
        working-directory: app
        run: yarn add react-native-reanimated@https://github.com/software-mansion/react-native-reanimated.git#commit=${{ github.sha }}
      - name: Install test dependencies
        working-directory: app
        run: yarn add react-native-v8 v8-android-jit
      - name: Configure V8
        run: node reanimated_repo/.github/workflows/helper/configureV8.js
      - name: Build Android app
        working-directory: app/android
        run: ./gradlew assembleDebug --console=plain
