name: Reanimated Android validation
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths:
      - '.github/workflows/reanimated-android-validation.yml'
      - 'packages/react-native-reanimated/android/src/main/java/**'
      - 'packages/react-native-reanimated/android/build.gradle'
      - 'packages/react-native-reanimated/scripts/cpplint.sh'
      - 'packages/react-native-reanimated/Common/cpp/**'
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - '.github/workflows/reanimated-android-validation.yml'
      - 'packages/react-native-reanimated/android/src/main/java/**'
      - 'packages/react-native-reanimated/android/build.gradle'
      - 'packages/react-native-reanimated/scripts/cpplint.sh'
      - 'packages/react-native-reanimated/Common/cpp/**'
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    concurrency:
      group: validate-java-${{ github.ref }}
      cancel-in-progress: true
    env:
      REANIMATED_DIR: packages/react-native-reanimated
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Java 17
        # Using older versions of Java might cause the lint step to throw
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cpplint==1.6.1
          pip install cmakelang==0.6.13

      - name: Clear annotations
        run: .github/workflows/helper/clear-annotations.sh

      - name: Install monorepo node dependencies
        run: yarn install --immutable
      - name: Build Reanimated package
        working-directory: ${{ env.REANIMATED_DIR }}
        run: yarn build

      - name: Lint Android
        working-directory: ${{ env.REANIMATED_DIR }}
        run: yarn lint:android
