name: Test TypeScript and Lint in root
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
  merge_group:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    concurrency:
      group: static-root-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - name: Clear annotations
        run: .github/workflows/helper/clear-annotations.sh

      - name: Install monorepo node dependencies
        run: yarn install
      - name: Install Reanimated node dependencies
        working-directory: packages/react-native-reanimated
        run: yarn install
      - name: Build Reanimated package
        working-directory: packages/react-native-reanimated
        run: yarn build

      - name: Check types
        working-directory: packages/react-native-reanimated
        run: yarn type:check:all
      - name: Lint reanimated
        working-directory: packages/react-native-reanimated
        run: yarn lint:js
      - name: Lint app-common
        working-directory: packages/react-native-reanimated
        run: yarn lint:app
      - name: Find unused code
        working-directory: packages/react-native-reanimated
        run: yarn find-unused-code:js
      - name: Find circular dependencies
        working-directory: packages/react-native-reanimated
        run: yarn circular-dependency-check
      - name: Check use strict
        working-directory: packages/react-native-reanimated
        run: yarn use-strict-check
      - name: Run jest unit tests
        working-directory: packages/react-native-reanimated
        run: yarn test:unit
