name: Test TypeScript and Lint
on:
  pull_request:
    paths:
      - '.github/workflows/static-root-checks.yml'
      - 'src/**'
      - '*'
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    concurrency:
      group: static-root-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install node dependencies ðŸ§¶
        run: yarn
      - name: Check types
        run: yarn tsc --noEmit
      - name: Check api
        run: yarn type:check-api
      - name: Lint
        run: yarn lint:js
      - name: Find unused code
        run: yarn ind-unused-code:js
      - name: Find circular dependencies
        run: yarn circular_dependency_check
      - name: Run jest unit tests
        run: yarn test:unit
