name: Use frameworks Reanimated build check [Nightly]
env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: 0
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths:
      - .github/workflows/use-frameworks-reanimated-build-check-nightly.yml
  schedule:
    - cron: '37 19 * * *'
  workflow_call:
  workflow_dispatch:

jobs:
  use-frameworks-reanimated-build-check-nightly:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: macos-14
    concurrency:
      group: use-${{matrix.type}}-frameworks-reanimated-build-check-nightly-${{ github.ref }}
      cancel-in-progress: true
    env:
      APP_NAME: app
    strategy:
      matrix:
        type: [static, dynamic]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - name: Setup Yarn
        # Sometimes `npx @react-native-community/cli init` fails at random.
        # Pre-installing it with Yarn seems to improve stability.
        run: corepack enable && yarn init
      - name: Install React Native
        run: yarn add @react-native-community/cli
      - name: Create app
        run: yarn rnc-cli init ${{ env.APP_NAME }} --skip-install --install-pods false --skip-git-init
      - name: Setup Yarn Modern in app
        working-directory: ${{ env.APP_NAME }}
        run: |
          touch yarn.lock
          yarn set version berry
          yarn config set nodeLinker node-modules
      - name: Install dependencies
        working-directory: ${{ env.APP_NAME }}
        run: yarn install
      - name: Install Reanimated
        working-directory: ${{ env.APP_NAME }}
        run: yarn add "react-native-reanimated@https://github.com/software-mansion/react-native-reanimated.git#workspace=react-native-reanimated&commit=${{ github.sha }}"
      - name: Install Worklets
        working-directory: ${{ env.APP_NAME }}
        run: yarn add "react-native-worklets@https://github.com/software-mansion/react-native-reanimated.git#workspace=react-native-worklets&commit=${{ github.sha }}"
      - name: Install ${{matrix.type}} Pods
        working-directory: ${{env.APP_NAME}}/ios
        run: export USE_FRAMEWORKS=${{matrix.type}} && bundle install && bundle exec pod update
      - name: Build app
        working-directory: ${{env.APP_NAME}}/ios
        run: xcodebuild -workspace ${{env.APP_NAME}}.xcworkspace -scheme ${{env.APP_NAME}} -configuration Debug -destination 'generic/platform=iOS Simulator' build | xcpretty
