name: V8 Reanimated build check [Nightly]
env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: 0
on:
  pull_request:
    paths:
      - .github/workflows/V8-reanimated-build-check-nightly.yml
      - .github/workflows/helper/configureV8.js
  schedule:
    - cron: '37 19 * * *'
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    concurrency:
      group: build-v8-${{ github.ref }}
      cancel-in-progress: true
    env:
      APP_NAME: app
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          path: 'reanimated_repo'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Create React Native App
        run: npx react-native init ${{ env.APP_NAME }} --skip-install
      - name: Setup Yarn Modern
        working-directory: ${{ env.APP_NAME }}
        run: touch yarn.lock && corepack enable && yarn set version berry
      - name: Install dependencies
        working-directory: ${{ env.APP_NAME }}
        run: yarn install
      - name: Debug print
        working-directory: ${{ env.APP_NAME }}
        run: ls node_modules && ls node_modules/@react-native && ls node_modules/@react-native/gradle-plugin
      - name: Install Reanimated
        working-directory: ${{ env.APP_NAME }}
        run: yarn add "react-native-reanimated@https://github.com/software-mansion/react-native-reanimated.git#workspace=react-native-reanimated&commit=${{ github.sha }}"
      - name: Install test dependencies
        working-directory: ${{ env.APP_NAME }}
        run: yarn add react-native-v8 v8-android-jit
      - name: Debug print
        working-directory: ${{ env.APP_NAME }}
        run: ls node_modules && ls node_modules/@react-native && ls node_modules/@react-native/gradle-plugin
      - name: Configure V8
        run: node reanimated_repo/.github/workflows/helper/configureV8.js
      - name: Build Android
        working-directory: ${{ env.APP_NAME }}/android
        run: ./gradlew assembleDebug --console=plain
