name: Java Lint
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths:
      - ".github/workflows/validate-java.yml"
      - "packages/react-native-reanimated/android/src/main/java/**"
      - "packages/react-native-reanimated/android/build.gradle"
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - ".github/workflows/validate-java.yml"
      - "packages/react-native-reanimated/android/src/main/java/**"
      - "packages/react-native-reanimated/android/build.gradle"

jobs:
  check:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    concurrency:
      group: validate-java-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
      - name: Clear annotations
        run: .github/helper/clear-annotations.sh

      - name: Install monorepo node dependencies
        run: yarn install
      - name: Install Reanimated node dependencies
        working-directory: packages/react-native-reanimated
        run: yarn

      - name: Lint Java
        working-directory: packages/react-native-reanimated
        run: yarn lint:java
