name: Windows hosted app Reanimated build check [Nightly]
env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: 0
on:
  pull_request:
    paths:
      - .github/workflows/windows-hosted-app-reanimated-build-check-nightly.yml
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: windows-latest
    concurrency:
      group: build-on-windows-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Create React Native App
        run:  npx @react-native-community/cli init app
      - name: Install dependencies
        working-directory: app
        run: yarn
      - name: Install Reanimated
        working-directory: app
        run: yarn add react-native-reanimated@https://github.com/software-mansion/react-native-reanimated.git#commit=${{ github.sha }}
      - name: Build Android App
        working-directory: app/android
        run: ./gradlew assembleDebug --console=plain
