name: Worklets static checks
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  worklets-static-checks:
    if: github.repository == 'software-mansion/react-native-reanimated'
    env:
      PACKAGE_PATH: packages/react-native-worklets
    runs-on: ubuntu-latest
    concurrency:
      group: worklets-static-checks-${{ github.ref }}
      cancel-in-progress: true
    steps:
      # Setup VM
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
      - name: Clear annotations
        run: .github/workflows/helper/clear-annotations.sh

      # Setup repo
      - name: Install monorepo node dependencies
        run: yarn install --immutable
      - name: Build Worklets package
        run: yarn workspace react-native-worklets build
      - name: Build Reanimated package
        # Needed for types for TypeScript checks in Example Apps
        run: yarn workspace react-native-reanimated build

      # Checks
      - name: Validate peer dependency versions
        working-directory: ${{ env.PACKAGE_PATH }}
        run: yarn validate-peers
      - name: Check TypeScript types
        working-directory: ${{ env.PACKAGE_PATH }}
        run: yarn type:check
      - name: Lint JavaScript
        working-directory: ${{ env.PACKAGE_PATH }}
        run: yarn lint:js
      - name: Find circular dependencies
        working-directory: ${{ env.PACKAGE_PATH }}
        run: yarn circular-dependency-check
      - name: Run Jest unit tests
        working-directory: ${{ env.PACKAGE_PATH }}
        run: yarn test
      - name: Check web tree-shakability
        working-directory: ${{ env.PACKAGE_PATH }}
        run: yarn tree-shake:check:web
