name: Worklets Bundle Mode build check
env:
  YARN_ENABLE_HARDENED_MODE: 0
  YARN_ENABLE_IMMUTABLE_INSTALLS: 0
on:
  pull_request:
    paths:
      - .github/workflows/worklets-bundle-mode-build-check.yml
      - .github/workflows/example-ios-build-check.yml
      - .github/workflows/example-android-build-check.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/worklets-bundle-mode-build-check.yml
      - .github/workflows/example-ios-build-check.yml
      - .github/workflows/example-android-build-check.yml
  workflow_call:
  workflow_dispatch:

jobs:
  worklets-bundle-mode-build-check-ios:
    if: github.repository == 'software-mansion/react-native-reanimated'
    uses: ./.github/workflows/example-ios-build-check.yml
    with:
      bundleMode: true

  worklets-bundle-mode-build-check-android:
    if: github.repository == 'software-mansion/react-native-reanimated'
    uses: ./.github/workflows/example-android-build-check.yml
    with:
      bundleMode: true
